apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
        - image: {{ .Values.imagetag }}
          name: nvtest-backend
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "6Gi"
              cpu: "6"